name: NodeJS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        echo '${{ secrets.DOT_ENV }}' > .env
        npm install
        npx remix vite:build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: "remix-app-${{ matrix.node-version }}"
        path: |
          ./build
          ./package.json
          ./package-lock.json
          ./vite.config.ts

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: remix-app-22.x

      - name: prepare uploading
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          proxy_host:  ${{ secrets.PROXY_HOST }}
          proxy_port:  ${{ secrets.PROXY_PORT }}
          proxy_username:  ${{ secrets.PROXY_USERNAME }}
          proxy_passphrase:  ${{ secrets.PASSPHRASE }}
          proxy_key:  ${{ secrets.KEY }}
          script: ${{ secrets.PREPARE_CMD }}

      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          proxy_host:  ${{ secrets.PROXY_HOST }}
          proxy_port:  ${{ secrets.PROXY_PORT }}
          proxy_username:  ${{ secrets.PROXY_USERNAME }}
          proxy_passphrase:  ${{ secrets.PASSPHRASE }}
          proxy_key:  ${{ secrets.KEY }}
          source: "./build,./package.json,./package-lock.json,./vite.config.ts"
          target: ${{ secrets.DST_DIR_PATH }}

      - name: restart containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          proxy_host:  ${{ secrets.PROXY_HOST }}
          proxy_port:  ${{ secrets.PROXY_PORT }}
          proxy_username:  ${{ secrets.PROXY_USERNAME }}
          proxy_passphrase:  ${{ secrets.PASSPHRASE }}
          proxy_key:  ${{ secrets.KEY }}
          script: ${{ secrets.RESTART_CMD }}

